[project]
name = "remi-das"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dascore>=0.1.13",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "pre-commit>=4.5.1",
]
